/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check process liveness
         * @description Lightweight process check. It does not contact PostgreSQL, ChromaDB, embedding models, or answer-generation providers.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check deployment readiness
         * @description Read-only PostgreSQL and ChromaDB accessibility checks. LLM providers are informational and never gate readiness.
         */
        get: operations["readiness_check_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a policy PDF
         * @description Validate, store, extract, chunk, embed, and index one PDF with durable metadata.
         */
        post: operations["upload_document_api_v1_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List document metadata */
        get: operations["list_documents_api_v1_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get document metadata */
        get: operations["get_document_api_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ingestion lifecycle status */
        get: operations["get_document_status_api_v1_documents__document_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search indexed evidence */
        post: operations["search_documents_api_v1_documents_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retrieve gated citation evidence */
        post: operations["retrieve_document_evidence_api_v1_documents_evidence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask an evidence-gated policy question
         * @description Return a supported answer or safe fallback with page-level provenance and confidence.
         */
        post: operations["ask_document_question_api_v1_documents_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the latest evaluation artifact */
        get: operations["get_latest_evaluation_api_v1_evaluations_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/latest.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the latest evaluation cases as CSV */
        get: operations["download_latest_evaluation_csv_api_v1_evaluations_latest_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_document_api_v1_documents_upload_post */
        Body_upload_document_api_v1_documents_upload_post: {
            /** File */
            file: string;
        };
        /** CitationCard */
        CitationCard: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Page Number */
            page_number: number;
            /** Section Title */
            section_title?: string | null;
            /** Chunk Index */
            chunk_index: number;
            /** Excerpt */
            excerpt: string;
            /** Retrieval Score */
            retrieval_score: number;
        };
        /** ConfidenceBreakdown */
        ConfidenceBreakdown: {
            /** Answerability Score */
            answerability_score: number;
            /** Top Retrieval Score */
            top_retrieval_score: number;
            /** Average Retrieval Score */
            average_retrieval_score: number;
            /** Retrieval Margin */
            retrieval_margin: number;
            /** Lexical Coverage */
            lexical_coverage: number;
            /** Top Chunk Lexical Coverage */
            top_chunk_lexical_coverage: number;
            /** Numeric Consistency */
            numeric_consistency?: number | null;
            /** Numeric Mismatch */
            numeric_mismatch: boolean;
            /** Query Numeric Claims */
            query_numeric_claims: string[];
            /** Evidence Numeric Claims */
            evidence_numeric_claims: string[];
            /** Missing Numeric Claims */
            missing_numeric_claims: string[];
            /** Scope Risk */
            scope_risk: boolean;
            /** Scope Risk Reason */
            scope_risk_reason?: string | null;
            /** Matched Query Terms */
            matched_query_terms: string[];
            /** Missing Query Terms */
            missing_query_terms: string[];
            /** Direct Support */
            direct_support: boolean;
            /** Decision Reasons */
            decision_reasons: string[];
        };
        /** DependencyCheck */
        DependencyCheck: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "unavailable";
        };
        /** DocumentAnswerRequest */
        DocumentAnswerRequest: {
            /** Question */
            question: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /** DocumentAnswerResponse */
        DocumentAnswerResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Answer Ready */
            answer_ready: boolean;
            /** Evidence Status */
            evidence_status: string;
            /** Confidence Score */
            confidence_score: number;
            confidence_breakdown?: components["schemas"]["ConfidenceBreakdown"] | null;
            /** Citation Count */
            citation_count: number;
            /** Citations */
            citations: components["schemas"]["CitationCard"][];
            /** Llm Provider */
            llm_provider: string;
            /** Model Name */
            model_name?: string | null;
            /**
             * Fallback Used
             * @default false
             */
            fallback_used: boolean;
        };
        /** DocumentChunk */
        DocumentChunk: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Page Number */
            page_number: number;
            /** Chunk Index */
            chunk_index: number;
            /** Section Title */
            section_title?: string | null;
            /** Text */
            text: string;
            /** Char Count */
            char_count: number;
        };
        /** DocumentDetailResponse */
        DocumentDetailResponse: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            status: components["schemas"]["DocumentStatus"];
            processing_stage: components["schemas"]["DocumentProcessingStage"];
            /** Page Count */
            page_count?: number | null;
            /** Character Count */
            character_count?: number | null;
            /** Chunk Count */
            chunk_count?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Indexed At */
            indexed_at?: string | null;
            /** Chroma Collection */
            chroma_collection?: string | null;
            /** Embedding Model */
            embedding_model?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
        };
        /** DocumentEvidenceRequest */
        DocumentEvidenceRequest: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /** DocumentEvidenceResponse */
        DocumentEvidenceResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Query */
            query: string;
            /** Top K */
            top_k: number;
            /** Answer Ready */
            answer_ready: boolean;
            /** Evidence Status */
            evidence_status: string;
            /** Confidence Score */
            confidence_score: number;
            /** Top Retrieval Score */
            top_retrieval_score: number;
            /** Average Retrieval Score */
            average_retrieval_score: number;
            /** Min Retrieval Score */
            min_retrieval_score: number;
            confidence_breakdown?: components["schemas"]["ConfidenceBreakdown"] | null;
            /** Citation Count */
            citation_count: number;
            /** Citations */
            citations: components["schemas"]["CitationCard"][];
            /** Fallback Message */
            fallback_message?: string | null;
        };
        /** DocumentIngestionResponse */
        DocumentIngestionResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Page Count */
            page_count: number;
            /** Total Characters */
            total_characters: number;
            /** Is Text Extractable */
            is_text_extractable: boolean;
            /** Chunk Count */
            chunk_count: number;
            /** Stored Chunk Count */
            stored_chunk_count: number;
            /** Collection Name */
            collection_name: string;
            /** Preview Text */
            preview_text: string;
            /** Sample Chunks */
            sample_chunks: components["schemas"]["DocumentChunk"][];
            /** Message */
            message: string;
            /** @default ready */
            status: components["schemas"]["DocumentStatus"];
            /** @default complete */
            processing_stage: components["schemas"]["DocumentProcessingStage"];
            /** Character Count */
            character_count?: number | null;
            /**
             * Duplicate
             * @default false
             */
            duplicate: boolean;
            /** Created At */
            created_at?: string | null;
            /** Indexed At */
            indexed_at?: string | null;
        };
        /** DocumentListResponse */
        DocumentListResponse: {
            /** Items */
            items: components["schemas"]["DocumentSummaryResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * DocumentProcessingStage
         * @enum {string}
         */
        DocumentProcessingStage: "received" | "stored" | "extracting" | "cleaning" | "chunking" | "embedding" | "indexing" | "complete" | "failed";
        /** DocumentSearchRequest */
        DocumentSearchRequest: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /** DocumentSearchResponse */
        DocumentSearchResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Query */
            query: string;
            /** Top K */
            top_k: number;
            /** Result Count */
            result_count: number;
            /** Results */
            results: components["schemas"]["DocumentSearchResult"][];
        };
        /** DocumentSearchResult */
        DocumentSearchResult: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Page Number */
            page_number: number;
            /** Chunk Index */
            chunk_index: number;
            /** Section Title */
            section_title?: string | null;
            /** Text */
            text: string;
            /** Char Count */
            char_count: number;
            /** Score */
            score: number;
        };
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "processing" | "ready" | "failed";
        /** DocumentStatusResponse */
        DocumentStatusResponse: {
            /** Document Id */
            document_id: string;
            status: components["schemas"]["DocumentStatus"];
            processing_stage: components["schemas"]["DocumentProcessingStage"];
            /** Page Count */
            page_count?: number | null;
            /** Chunk Count */
            chunk_count?: number | null;
            /** Error Code */
            error_code?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DocumentSummaryResponse */
        DocumentSummaryResponse: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            status: components["schemas"]["DocumentStatus"];
            processing_stage: components["schemas"]["DocumentProcessingStage"];
            /** Page Count */
            page_count?: number | null;
            /** Character Count */
            character_count?: number | null;
            /** Chunk Count */
            chunk_count?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Indexed At */
            indexed_at?: string | null;
        };
        /** EvaluationArtifactMetadata */
        EvaluationArtifactMetadata: {
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Question Count */
            question_count: number;
            /** Benchmark Question Count */
            benchmark_question_count?: number | null;
            /** Is Partial */
            is_partial: boolean;
        };
        /** EvaluationArtifactResponse */
        EvaluationArtifactResponse: {
            artifact: components["schemas"]["EvaluationArtifactMetadata"];
            run: components["schemas"]["EvaluationRunMetadata"];
            summary: components["schemas"]["EvaluationSummary"];
            /** Results */
            results: components["schemas"]["EvaluationCase"][];
        };
        /** EvaluationBackendHealth */
        EvaluationBackendHealth: {
            /** Latency Ms */
            latency_ms?: number | null;
            /** Status */
            status?: string | null;
        };
        /** EvaluationCase */
        EvaluationCase: {
            /** Id */
            id: string;
            /** Question */
            question: string;
            /** Category */
            category: string;
            /** Difficulty */
            difficulty: string;
            /** Evaluation Focus */
            evaluation_focus?: string[];
            /** Should Answer */
            should_answer: boolean;
            /** Answer Ready */
            answer_ready: boolean;
            /** Readiness Correct */
            readiness_correct: boolean;
            /** Evidence Status */
            evidence_status: string;
            /** Confidence Score */
            confidence_score: number;
            confidence_breakdown?: components["schemas"]["EvaluationConfidenceBreakdown"] | null;
            /** Answerability Score */
            answerability_score?: number | null;
            /** Top Retrieval Score */
            top_retrieval_score?: number | null;
            /** Average Retrieval Score */
            average_retrieval_score?: number | null;
            /** Retrieval Margin */
            retrieval_margin?: number | null;
            /** Lexical Coverage */
            lexical_coverage?: number | null;
            /** Top Chunk Lexical Coverage */
            top_chunk_lexical_coverage?: number | null;
            /** Numeric Consistency */
            numeric_consistency?: number | null;
            /**
             * Numeric Mismatch
             * @default false
             */
            numeric_mismatch: boolean;
            /**
             * Scope Risk
             * @default false
             */
            scope_risk: boolean;
            /** Direct Support */
            direct_support?: boolean | null;
            /** Decision Reasons */
            decision_reasons?: string[];
            /** Expected Pages */
            expected_pages?: number[];
            /** Retrieved Pages */
            retrieved_pages?: number[];
            /** Page Hit */
            page_hit?: boolean | null;
            /** Expected Answer Keywords */
            expected_answer_keywords?: string[];
            /** Matched Keywords */
            matched_keywords?: string[];
            /** Missing Keywords */
            missing_keywords?: string[];
            /** Keyword Match Score */
            keyword_match_score?: number | null;
            /** Answer */
            answer: string;
            /** Fallback Used */
            fallback_used: boolean;
            /** Fallback Correct */
            fallback_correct?: boolean | null;
            /** Citation Count */
            citation_count: number;
            /** Retrieved Filenames */
            retrieved_filenames?: string[];
            /** Citation Scores */
            citation_scores?: number[];
            /** Top Citation Score */
            top_citation_score?: number | null;
            /** Average Citation Score */
            average_citation_score?: number | null;
            /**
             * Duplicate Citation Count
             * @default 0
             */
            duplicate_citation_count: number;
            /** Latency Ms */
            latency_ms: number;
            /** Llm Provider */
            llm_provider: string;
            /** Model Name */
            model_name?: string | null;
            /** Case Passed */
            case_passed: boolean;
            /** Error Type */
            error_type?: string | null;
            /** Provider Fallback Used */
            provider_fallback_used?: boolean | null;
            /** Generation Attempt Count */
            generation_attempt_count?: number | null;
            /** Generation Error Type */
            generation_error_type?: string | null;
        };
        /** EvaluationConfidenceBreakdown */
        EvaluationConfidenceBreakdown: {
            /** Answerability Score */
            answerability_score?: number | null;
            /** Top Retrieval Score */
            top_retrieval_score?: number | null;
            /** Average Retrieval Score */
            average_retrieval_score?: number | null;
            /** Retrieval Margin */
            retrieval_margin?: number | null;
            /** Lexical Coverage */
            lexical_coverage?: number | null;
            /** Top Chunk Lexical Coverage */
            top_chunk_lexical_coverage?: number | null;
            /** Numeric Consistency */
            numeric_consistency?: number | null;
            /**
             * Numeric Mismatch
             * @default false
             */
            numeric_mismatch: boolean;
            /**
             * Scope Risk
             * @default false
             */
            scope_risk: boolean;
            /** Direct Support */
            direct_support?: boolean | null;
            /** Query Numeric Claims */
            query_numeric_claims?: string[];
            /** Evidence Numeric Claims */
            evidence_numeric_claims?: string[];
            /** Missing Numeric Claims */
            missing_numeric_claims?: string[];
            /** Matched Query Terms */
            matched_query_terms?: string[];
            /** Missing Query Terms */
            missing_query_terms?: string[];
            /** Decision Reasons */
            decision_reasons?: string[];
            /** Scope Risk Reason */
            scope_risk_reason?: string | null;
        };
        /** EvaluationRunMetadata */
        EvaluationRunMetadata: {
            /** Run Id */
            run_id: string;
            /** Started At Utc */
            started_at_utc?: string | null;
            /** Completed At Utc */
            completed_at_utc?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * Backend Base Label
             * @default Configured backend
             */
            backend_base_label: string;
            /** Endpoint */
            endpoint?: string | null;
            /** Dataset Path */
            dataset_path?: string | null;
            /** Dataset Sha256 */
            dataset_sha256?: string | null;
            /** Top K */
            top_k?: number | null;
            /** Timeout Seconds */
            timeout_seconds?: number | null;
            /** Request Delay Seconds */
            request_delay_seconds?: number | null;
            /** Question Count */
            question_count: number;
            backend_health?: components["schemas"]["EvaluationBackendHealth"] | null;
            /**
             * Duplicate Citation Warning
             * @default false
             */
            duplicate_citation_warning: boolean;
            /** Question Id */
            question_id?: string | null;
            /** Limit */
            limit?: number | null;
        };
        /** EvaluationSummary */
        EvaluationSummary: {
            /** Total Questions */
            total_questions: number;
            /** Supported Questions */
            supported_questions: number;
            /** Unsupported Questions */
            unsupported_questions: number;
            /** Passed Questions */
            passed_questions: number;
            /** Failed Questions Count */
            failed_questions_count: number;
            /** Request Error Count */
            request_error_count: number;
            /** Answer Readiness Accuracy */
            answer_readiness_accuracy: number;
            /** Fallback Accuracy */
            fallback_accuracy: number;
            /** Retrieval Page Hit Rate */
            retrieval_page_hit_rate: number;
            /** Keyword Match Rate */
            keyword_match_rate: number;
            /** Average Confidence */
            average_confidence: number;
            /** Average Supported Confidence */
            average_supported_confidence: number;
            /** Average Latency Ms */
            average_latency_ms: number;
            /** Average Citation Count */
            average_citation_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LivenessResponse */
        LivenessResponse: {
            /**
             * Status
             * @default operational
             * @constant
             */
            status: "operational";
            /** Service */
            service: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
        };
        /** ProviderMode */
        ProviderMode: {
            /**
             * Status
             * @enum {string}
             */
            status: "configured" | "citation_only_fallback";
            /**
             * Provider
             * @enum {string}
             */
            provider: "groq" | "openai" | "none";
        };
        /** ReadinessChecks */
        ReadinessChecks: {
            database: components["schemas"]["DependencyCheck"];
            vector_store: components["schemas"]["DependencyCheck"];
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            checks: components["schemas"]["ReadinessChecks"];
            answer_generation: components["schemas"]["ProviderMode"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_check_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Required dependency unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    upload_document_api_v1_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentIngestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_documents_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: components["schemas"]["DocumentStatus"] | null;
                filename?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_status_api_v1_documents__document_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_documents_api_v1_documents_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_document_evidence_api_v1_documents_evidence_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentEvidenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentEvidenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_document_question_api_v1_documents_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentAnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_evaluation_api_v1_evaluations_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationArtifactResponse"];
                };
            };
        };
    };
    download_latest_evaluation_csv_api_v1_evaluations_latest_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
