/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Lightweight backend health check.
         *
         *     This endpoint does not call external LLM providers or run expensive checks.
         *     It confirms that the FastAPI app is running and exposes safe RAG config details.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_v1_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Documents */
        post: operations["search_documents_api_v1_documents_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retrieve Document Evidence */
        post: operations["retrieve_document_evidence_api_v1_documents_evidence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Document Question */
        post: operations["ask_document_question_api_v1_documents_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_document_api_v1_documents_upload_post */
        Body_upload_document_api_v1_documents_upload_post: {
            /** File */
            file: string;
        };
        /** CitationCard */
        CitationCard: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Page Number */
            page_number: number;
            /** Section Title */
            section_title?: string | null;
            /** Chunk Index */
            chunk_index: number;
            /** Excerpt */
            excerpt: string;
            /** Retrieval Score */
            retrieval_score: number;
        };
        /** ConfidenceBreakdown */
        ConfidenceBreakdown: {
            /** Answerability Score */
            answerability_score: number;
            /** Top Retrieval Score */
            top_retrieval_score: number;
            /** Average Retrieval Score */
            average_retrieval_score: number;
            /** Retrieval Margin */
            retrieval_margin: number;
            /** Lexical Coverage */
            lexical_coverage: number;
            /** Top Chunk Lexical Coverage */
            top_chunk_lexical_coverage: number;
            /** Numeric Consistency */
            numeric_consistency?: number | null;
            /** Numeric Mismatch */
            numeric_mismatch: boolean;
            /** Query Numeric Claims */
            query_numeric_claims: string[];
            /** Evidence Numeric Claims */
            evidence_numeric_claims: string[];
            /** Missing Numeric Claims */
            missing_numeric_claims: string[];
            /** Scope Risk */
            scope_risk: boolean;
            /** Scope Risk Reason */
            scope_risk_reason?: string | null;
            /** Matched Query Terms */
            matched_query_terms: string[];
            /** Missing Query Terms */
            missing_query_terms: string[];
            /** Direct Support */
            direct_support: boolean;
            /** Decision Reasons */
            decision_reasons: string[];
        };
        /** DocumentAnswerRequest */
        DocumentAnswerRequest: {
            /** Question */
            question: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /** DocumentAnswerResponse */
        DocumentAnswerResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Answer Ready */
            answer_ready: boolean;
            /** Evidence Status */
            evidence_status: string;
            /** Confidence Score */
            confidence_score: number;
            confidence_breakdown?: components["schemas"]["ConfidenceBreakdown"] | null;
            /** Citation Count */
            citation_count: number;
            /** Citations */
            citations: components["schemas"]["CitationCard"][];
            /** Llm Provider */
            llm_provider: string;
            /** Model Name */
            model_name?: string | null;
            /**
             * Fallback Used
             * @default false
             */
            fallback_used: boolean;
        };
        /** DocumentChunk */
        DocumentChunk: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Page Number */
            page_number: number;
            /** Chunk Index */
            chunk_index: number;
            /** Section Title */
            section_title?: string | null;
            /** Text */
            text: string;
            /** Char Count */
            char_count: number;
        };
        /** DocumentEvidenceRequest */
        DocumentEvidenceRequest: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /** DocumentEvidenceResponse */
        DocumentEvidenceResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Query */
            query: string;
            /** Top K */
            top_k: number;
            /** Answer Ready */
            answer_ready: boolean;
            /** Evidence Status */
            evidence_status: string;
            /** Confidence Score */
            confidence_score: number;
            /** Top Retrieval Score */
            top_retrieval_score: number;
            /** Average Retrieval Score */
            average_retrieval_score: number;
            /** Min Retrieval Score */
            min_retrieval_score: number;
            confidence_breakdown?: components["schemas"]["ConfidenceBreakdown"] | null;
            /** Citation Count */
            citation_count: number;
            /** Citations */
            citations: components["schemas"]["CitationCard"][];
            /** Fallback Message */
            fallback_message?: string | null;
        };
        /** DocumentIngestionResponse */
        DocumentIngestionResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Page Count */
            page_count: number;
            /** Total Characters */
            total_characters: number;
            /** Is Text Extractable */
            is_text_extractable: boolean;
            /** Chunk Count */
            chunk_count: number;
            /** Stored Chunk Count */
            stored_chunk_count: number;
            /** Collection Name */
            collection_name: string;
            /** Preview Text */
            preview_text: string;
            /** Sample Chunks */
            sample_chunks: components["schemas"]["DocumentChunk"][];
            /** Message */
            message: string;
        };
        /** DocumentSearchRequest */
        DocumentSearchRequest: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /** DocumentSearchResponse */
        DocumentSearchResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Query */
            query: string;
            /** Top K */
            top_k: number;
            /** Result Count */
            result_count: number;
            /** Results */
            results: components["schemas"]["DocumentSearchResult"][];
        };
        /** DocumentSearchResult */
        DocumentSearchResult: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Page Number */
            page_number: number;
            /** Chunk Index */
            chunk_index: number;
            /** Section Title */
            section_title?: string | null;
            /** Text */
            text: string;
            /** Char Count */
            char_count: number;
            /** Score */
            score: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    upload_document_api_v1_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentIngestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_documents_api_v1_documents_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_document_evidence_api_v1_documents_evidence_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentEvidenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentEvidenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_document_question_api_v1_documents_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentAnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
