/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Lightweight backend health check.
         *
         *     This endpoint does not call external LLM providers or run expensive checks.
         *     It confirms that the FastAPI app is running and exposes safe RAG config details.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_v1_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Documents */
        post: operations["search_documents_api_v1_documents_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retrieve Document Evidence */
        post: operations["retrieve_document_evidence_api_v1_documents_evidence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Document Question */
        post: operations["ask_document_question_api_v1_documents_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Evaluation */
        get: operations["get_latest_evaluation_api_v1_evaluations_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/latest.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Latest Evaluation Csv */
        get: operations["download_latest_evaluation_csv_api_v1_evaluations_latest_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_document_api_v1_documents_upload_post */
        Body_upload_document_api_v1_documents_upload_post: {
            /** File */
            file: string;
        };
        /** CitationCard */
        CitationCard: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Page Number */
            page_number: number;
            /** Section Title */
            section_title?: string | null;
            /** Chunk Index */
            chunk_index: number;
            /** Excerpt */
            excerpt: string;
            /** Retrieval Score */
            retrieval_score: number;
        };
        /** ConfidenceBreakdown */
        ConfidenceBreakdown: {
            /** Answerability Score */
            answerability_score: number;
            /** Top Retrieval Score */
            top_retrieval_score: number;
            /** Average Retrieval Score */
            average_retrieval_score: number;
            /** Retrieval Margin */
            retrieval_margin: number;
            /** Lexical Coverage */
            lexical_coverage: number;
            /** Top Chunk Lexical Coverage */
            top_chunk_lexical_coverage: number;
            /** Numeric Consistency */
            numeric_consistency?: number | null;
            /** Numeric Mismatch */
            numeric_mismatch: boolean;
            /** Query Numeric Claims */
            query_numeric_claims: string[];
            /** Evidence Numeric Claims */
            evidence_numeric_claims: string[];
            /** Missing Numeric Claims */
            missing_numeric_claims: string[];
            /** Scope Risk */
            scope_risk: boolean;
            /** Scope Risk Reason */
            scope_risk_reason?: string | null;
            /** Matched Query Terms */
            matched_query_terms: string[];
            /** Missing Query Terms */
            missing_query_terms: string[];
            /** Direct Support */
            direct_support: boolean;
            /** Decision Reasons */
            decision_reasons: string[];
        };
        /** DocumentAnswerRequest */
        DocumentAnswerRequest: {
            /** Question */
            question: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /** DocumentAnswerResponse */
        DocumentAnswerResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Answer Ready */
            answer_ready: boolean;
            /** Evidence Status */
            evidence_status: string;
            /** Confidence Score */
            confidence_score: number;
            confidence_breakdown?: components["schemas"]["ConfidenceBreakdown"] | null;
            /** Citation Count */
            citation_count: number;
            /** Citations */
            citations: components["schemas"]["CitationCard"][];
            /** Llm Provider */
            llm_provider: string;
            /** Model Name */
            model_name?: string | null;
            /**
             * Fallback Used
             * @default false
             */
            fallback_used: boolean;
        };
        /** DocumentChunk */
        DocumentChunk: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Page Number */
            page_number: number;
            /** Chunk Index */
            chunk_index: number;
            /** Section Title */
            section_title?: string | null;
            /** Text */
            text: string;
            /** Char Count */
            char_count: number;
        };
        /** DocumentEvidenceRequest */
        DocumentEvidenceRequest: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /** DocumentEvidenceResponse */
        DocumentEvidenceResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Query */
            query: string;
            /** Top K */
            top_k: number;
            /** Answer Ready */
            answer_ready: boolean;
            /** Evidence Status */
            evidence_status: string;
            /** Confidence Score */
            confidence_score: number;
            /** Top Retrieval Score */
            top_retrieval_score: number;
            /** Average Retrieval Score */
            average_retrieval_score: number;
            /** Min Retrieval Score */
            min_retrieval_score: number;
            confidence_breakdown?: components["schemas"]["ConfidenceBreakdown"] | null;
            /** Citation Count */
            citation_count: number;
            /** Citations */
            citations: components["schemas"]["CitationCard"][];
            /** Fallback Message */
            fallback_message?: string | null;
        };
        /** DocumentIngestionResponse */
        DocumentIngestionResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Page Count */
            page_count: number;
            /** Total Characters */
            total_characters: number;
            /** Is Text Extractable */
            is_text_extractable: boolean;
            /** Chunk Count */
            chunk_count: number;
            /** Stored Chunk Count */
            stored_chunk_count: number;
            /** Collection Name */
            collection_name: string;
            /** Preview Text */
            preview_text: string;
            /** Sample Chunks */
            sample_chunks: components["schemas"]["DocumentChunk"][];
            /** Message */
            message: string;
        };
        /** DocumentSearchRequest */
        DocumentSearchRequest: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /** DocumentSearchResponse */
        DocumentSearchResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Query */
            query: string;
            /** Top K */
            top_k: number;
            /** Result Count */
            result_count: number;
            /** Results */
            results: components["schemas"]["DocumentSearchResult"][];
        };
        /** DocumentSearchResult */
        DocumentSearchResult: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Page Number */
            page_number: number;
            /** Chunk Index */
            chunk_index: number;
            /** Section Title */
            section_title?: string | null;
            /** Text */
            text: string;
            /** Char Count */
            char_count: number;
            /** Score */
            score: number;
        };
        /** EvaluationArtifactMetadata */
        EvaluationArtifactMetadata: {
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Question Count */
            question_count: number;
            /** Benchmark Question Count */
            benchmark_question_count?: number | null;
            /** Is Partial */
            is_partial: boolean;
        };
        /** EvaluationArtifactResponse */
        EvaluationArtifactResponse: {
            artifact: components["schemas"]["EvaluationArtifactMetadata"];
            run: components["schemas"]["EvaluationRunMetadata"];
            summary: components["schemas"]["EvaluationSummary"];
            /** Results */
            results: components["schemas"]["EvaluationCase"][];
        };
        /** EvaluationBackendHealth */
        EvaluationBackendHealth: {
            /** Latency Ms */
            latency_ms?: number | null;
            /** Status */
            status?: string | null;
        };
        /** EvaluationCase */
        EvaluationCase: {
            /** Id */
            id: string;
            /** Question */
            question: string;
            /** Category */
            category: string;
            /** Difficulty */
            difficulty: string;
            /** Evaluation Focus */
            evaluation_focus?: string[];
            /** Should Answer */
            should_answer: boolean;
            /** Answer Ready */
            answer_ready: boolean;
            /** Readiness Correct */
            readiness_correct: boolean;
            /** Evidence Status */
            evidence_status: string;
            /** Confidence Score */
            confidence_score: number;
            confidence_breakdown?: components["schemas"]["EvaluationConfidenceBreakdown"] | null;
            /** Answerability Score */
            answerability_score?: number | null;
            /** Top Retrieval Score */
            top_retrieval_score?: number | null;
            /** Average Retrieval Score */
            average_retrieval_score?: number | null;
            /** Retrieval Margin */
            retrieval_margin?: number | null;
            /** Lexical Coverage */
            lexical_coverage?: number | null;
            /** Top Chunk Lexical Coverage */
            top_chunk_lexical_coverage?: number | null;
            /** Numeric Consistency */
            numeric_consistency?: number | null;
            /**
             * Numeric Mismatch
             * @default false
             */
            numeric_mismatch: boolean;
            /**
             * Scope Risk
             * @default false
             */
            scope_risk: boolean;
            /** Direct Support */
            direct_support?: boolean | null;
            /** Decision Reasons */
            decision_reasons?: string[];
            /** Expected Pages */
            expected_pages?: number[];
            /** Retrieved Pages */
            retrieved_pages?: number[];
            /** Page Hit */
            page_hit?: boolean | null;
            /** Expected Answer Keywords */
            expected_answer_keywords?: string[];
            /** Matched Keywords */
            matched_keywords?: string[];
            /** Missing Keywords */
            missing_keywords?: string[];
            /** Keyword Match Score */
            keyword_match_score?: number | null;
            /** Answer */
            answer: string;
            /** Fallback Used */
            fallback_used: boolean;
            /** Fallback Correct */
            fallback_correct?: boolean | null;
            /** Citation Count */
            citation_count: number;
            /** Retrieved Filenames */
            retrieved_filenames?: string[];
            /** Citation Scores */
            citation_scores?: number[];
            /** Top Citation Score */
            top_citation_score?: number | null;
            /** Average Citation Score */
            average_citation_score?: number | null;
            /**
             * Duplicate Citation Count
             * @default 0
             */
            duplicate_citation_count: number;
            /** Latency Ms */
            latency_ms: number;
            /** Llm Provider */
            llm_provider: string;
            /** Model Name */
            model_name?: string | null;
            /** Case Passed */
            case_passed: boolean;
            /** Error Type */
            error_type?: string | null;
            /** Provider Fallback Used */
            provider_fallback_used?: boolean | null;
            /** Generation Attempt Count */
            generation_attempt_count?: number | null;
            /** Generation Error Type */
            generation_error_type?: string | null;
        };
        /** EvaluationConfidenceBreakdown */
        EvaluationConfidenceBreakdown: {
            /** Answerability Score */
            answerability_score?: number | null;
            /** Top Retrieval Score */
            top_retrieval_score?: number | null;
            /** Average Retrieval Score */
            average_retrieval_score?: number | null;
            /** Retrieval Margin */
            retrieval_margin?: number | null;
            /** Lexical Coverage */
            lexical_coverage?: number | null;
            /** Top Chunk Lexical Coverage */
            top_chunk_lexical_coverage?: number | null;
            /** Numeric Consistency */
            numeric_consistency?: number | null;
            /**
             * Numeric Mismatch
             * @default false
             */
            numeric_mismatch: boolean;
            /**
             * Scope Risk
             * @default false
             */
            scope_risk: boolean;
            /** Direct Support */
            direct_support?: boolean | null;
            /** Query Numeric Claims */
            query_numeric_claims?: string[];
            /** Evidence Numeric Claims */
            evidence_numeric_claims?: string[];
            /** Missing Numeric Claims */
            missing_numeric_claims?: string[];
            /** Matched Query Terms */
            matched_query_terms?: string[];
            /** Missing Query Terms */
            missing_query_terms?: string[];
            /** Decision Reasons */
            decision_reasons?: string[];
            /** Scope Risk Reason */
            scope_risk_reason?: string | null;
        };
        /** EvaluationRunMetadata */
        EvaluationRunMetadata: {
            /** Run Id */
            run_id: string;
            /** Started At Utc */
            started_at_utc?: string | null;
            /** Completed At Utc */
            completed_at_utc?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * Backend Base Label
             * @default Configured backend
             */
            backend_base_label: string;
            /** Endpoint */
            endpoint?: string | null;
            /** Dataset Path */
            dataset_path?: string | null;
            /** Dataset Sha256 */
            dataset_sha256?: string | null;
            /** Top K */
            top_k?: number | null;
            /** Timeout Seconds */
            timeout_seconds?: number | null;
            /** Request Delay Seconds */
            request_delay_seconds?: number | null;
            /** Question Count */
            question_count: number;
            backend_health?: components["schemas"]["EvaluationBackendHealth"] | null;
            /**
             * Duplicate Citation Warning
             * @default false
             */
            duplicate_citation_warning: boolean;
            /** Question Id */
            question_id?: string | null;
            /** Limit */
            limit?: number | null;
        };
        /** EvaluationSummary */
        EvaluationSummary: {
            /** Total Questions */
            total_questions: number;
            /** Supported Questions */
            supported_questions: number;
            /** Unsupported Questions */
            unsupported_questions: number;
            /** Passed Questions */
            passed_questions: number;
            /** Failed Questions Count */
            failed_questions_count: number;
            /** Request Error Count */
            request_error_count: number;
            /** Answer Readiness Accuracy */
            answer_readiness_accuracy: number;
            /** Fallback Accuracy */
            fallback_accuracy: number;
            /** Retrieval Page Hit Rate */
            retrieval_page_hit_rate: number;
            /** Keyword Match Rate */
            keyword_match_rate: number;
            /** Average Confidence */
            average_confidence: number;
            /** Average Supported Confidence */
            average_supported_confidence: number;
            /** Average Latency Ms */
            average_latency_ms: number;
            /** Average Citation Count */
            average_citation_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    upload_document_api_v1_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentIngestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_documents_api_v1_documents_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_document_evidence_api_v1_documents_evidence_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentEvidenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentEvidenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_document_question_api_v1_documents_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentAnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_evaluation_api_v1_evaluations_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationArtifactResponse"];
                };
            };
        };
    };
    download_latest_evaluation_csv_api_v1_evaluations_latest_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
